### ISSUE TITLE
Commit 95b2a52 on branch dev fails tests

### ISSUE THREAD

**Issue by Baashen** [rizac/stream2segment#47]
> ================================================================================== short test summary info ===================================================================================
> FAILED tests/download/test_u_download_01_events.py::Test::test_pbar1[sqlite] - KeyError: 'length'
> FAILED tests/download/test_u_download_01_events.py::Test::test_pbar2[sqlite-args0] - KeyError: 'length'
> FAILED tests/download/test_u_download_01_events.py::Test::test_pbar2[sqlite-args1] - KeyError: 'length'
> FAILED tests/download/test_u_download_01_events.py::Test::test_pbar2[sqlite-args2] - KeyError: 'length'
> FAILED tests/download/test_u_download_01_events.py::Test::test_pbar2[sqlite-args3] - KeyError: 'length'

**Comment by rizac** [comment]
`stream2segment.cli.get_porogressbar` was changed from 
```python
def get_progressbar(show:bool, **kw):
```
to
```python
def get_progressbar(length:int, **kw):
```
where now `length=0` behaves as `show=False`. All `test_pbar*` that rely in the old signature should be changed, I can fix them if needed and can be ignored for the moment.
